#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

n = int(input().strip())
a = list(map(int, input().strip().split(' ')))

if len(a) == 1:
    print(0)
    sys.exit()

total = {}
for i in a:
    if i in total:
        total[i] += 1
    else:
        total[i] = 1

index = total[a[0]]
value = total[a[1]]
for i in total:
    if total[i] > value:
        index = i
        value = total[i]

print(len(a) - value)

